name: Build for C Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Information
      run: |
        echo "Current Directory: $(pwd)"
        echo "Available Files:"
        ls -la

    - name: Set up build environment (Linux/Mac)
      if: runner.os != 'Windows'
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev uuid-dev clang
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          brew install sqlite3 ossp-luuid
        fi

        if [ "${{ matrix.compiler }}" == "clang" ]; then
          brew install -y clang
          sudo apt-get install -y clang
        fi

    - name: Set up build environment (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install mingw -y --yes
        powershell -Command "Invoke-WebRequest -Uri 'https://www.sqlite.org/2023/sqlite-dll-win32-x86-3390500.zip' -OutFile 'sqlite-dll-win32-x86-3390500.zip'"
        powershell -Command "Expand-Archive -Path 'sqlite-dll-win32-x86-3390500.zip' -DestinationPath 'C:\usr\local\lib'"

    - name: Build with ${{ matrix.compiler }}
      run: |
        cd src
        make clean
        make CC=${{ matrix.compiler }}

    - name: Upload binaries as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Binaries-${{ matrix.os }}-${{ matrix.compiler }}
        path: ./StockManager

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: "Release v1.0.0"
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./StockManager
        asset_name: StockManager
        asset_content_type: application/octet-stream


