name: Build project C for Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential sqlite3 libsqlite3-dev cmake

      - name: Configure and Build with CMake
        run: |
          mkdir -p build/app/db build/app/log  # Cria as pastas db e log
          cd build
          cmake ..
          cmake --build .

      - name: Package Binaries
        run: |
          if [ -f ./app/StockManager ]; then  # Altera o caminho para o executável
            tar -czvf StockManager-linux.tar.gz ./app
            echo "STOCKMANAGER_PACKAGE=StockManager-linux.tar.gz" >> $GITHUB_ENV
          else
            echo "StockManager binary not found!" >&2
            exit 1
          fi

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binaries-linux-gcc
          path: ${{ env.STOCKMANAGER_PACKAGE }}
