name: Build project C for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinGW and dependencies
        run: |
          choco install mingw --yes
          choco install sqlite --yes
          choco install make --yes
          choco install cmake --yes

      - name: Configure and Build with CMake
        run: |
          cd src
          mkdir build
          mkdir build/app
          mkdir -p build/app/db
          mkdir -p build/app/log
          cd build
          cmake ..
          cmake --build .

      - name: Package Binaries
        run: |
          if (Test-Path "./app/StockManager.exe") {
            Compress-Archive -Path "./app" -DestinationPath "StockManager-windows.zip"
            echo "STOCKMANAGER_PACKAGE=StockManager-windows.zip" >> $env:GITHUB_ENV
          } else {
            Write-Host "StockManager.exe binary not found!" -ErrorAction Stop
          }

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binaries-windows-gcc
          path: ${{ env.STOCKMANAGER_PACKAGE }}
